# Generated by Django 5.0 on 2025-11-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmusementPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('rides_available', models.IntegerField()),
                ('family_friendly', models.BooleanField(default=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_seats', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='perks/')),
            ],
        ),
        migrations.CreateModel(
            name='ComedyShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('comedian_name', models.CharField(max_length=100)),
                ('age_limit', models.PositiveIntegerField(default=18)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_seats', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='comedy/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('available_seats', models.PositiveIntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='LiveConcert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('artist_name', models.CharField(max_length=100)),
                ('music_genre', models.CharField(max_length=100)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vip_ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('available_seats', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='concerts/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('language', models.CharField(max_length=50)),
                ('duration', models.DurationField(help_text='Duration of the movie (HH:MM:SS)')),
                ('genre', models.CharField(max_length=100)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_seats', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
            ],
        ),
    ]
