# Generated by Django 5.0 on 2025-11-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_amusementpark_comedyshow_event_liveconcert_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedyshow',
            name='comedy_type',
            field=models.CharField(choices=[('Stand-up', 'Stand-up'), ('Improv', 'Improv'), ('Sketch', 'Sketch'), ('Roast', 'Roast')], default='Stand-up', max_length=50),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='duration',
            field=models.PositiveIntegerField(default=90, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='experience',
            field=models.CharField(default='Professional Comedian', max_length=100),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='popularity',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Trending', 'Trending'), ('New', 'New'), ('Sold Out', 'Sold Out')], default='Popular', max_length=20),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
    ]
