# Generated by Django 5.0 on 2025-11-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_comedyshow_comedy_type_comedyshow_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Trending', 'Trending'), ('New Release', 'New Release'), ('Blockbuster', 'Blockbuster')], default='Hot', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
    ]
