# Generated by Django 5.0 on 2025-11-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_movie_cast_movie_director_movie_popularity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.0, max_digits=3, null=True),
        ),
    ]
