# Generated by Django 5.0 on 2025-11-17 11:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_alter_movie_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(default='Screen 1', max_length=100)),
                ('total_rows', models.PositiveIntegerField(default=10)),
                ('seats_per_row', models.PositiveIntegerField(default=12)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='eventapp.movie')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Blocked', 'Blocked')], default='Available', max_length=20)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='eventapp.moviescreen')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=4)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.moviescreen')),
                ('seats', models.ManyToManyField(to='eventapp.theaterseat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.user')),
            ],
        ),
    ]
