# Generated by Django 5.0 on 2025-11-18 09:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_moviescreen_theaterseat_ticketbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviescreen',
            name='executive_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.2'), max_digits=4),
        ),
        migrations.AddField(
            model_name='moviescreen',
            name='executive_rows_end',
            field=models.PositiveIntegerField(default=6, help_text='Rows after premium to this number are executive'),
        ),
        migrations.AddField(
            model_name='moviescreen',
            name='normal_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='moviescreen',
            name='premium_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=4),
        ),
        migrations.AddField(
            model_name='moviescreen',
            name='premium_rows_end',
            field=models.PositiveIntegerField(default=3, help_text='Rows 1 to this number are premium'),
        ),
        migrations.AddField(
            model_name='theaterseat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='theaterseat',
            name='seat_type',
            field=models.CharField(choices=[('premium', 'premium'), ('executive', 'executive'), ('normal', 'normal')], default='normal', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='theaterseat',
            unique_together={('screen', 'row', 'number')},
        ),
    ]
