# Generated by Django 5.0 on 2025-11-18 11:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_moviescreen_executive_price_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviescreen',
            name='executive_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='moviescreen',
            name='normal_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='moviescreen',
            name='premium_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
