# Generated by Django 5.0 on 2025-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_alter_moviescreen_executive_price_multiplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveconcert',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='liveconcert',
            name='charity_fee',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
        ),
        migrations.AddField(
            model_name='liveconcert',
            name='convenience_fee',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=8),
        ),
        migrations.AddField(
            model_name='liveconcert',
            name='couples_ticket_price',
            field=models.DecimalField(decimal_places=2, default=1800, max_digits=8),
        ),
        migrations.AddField(
            model_name='liveconcert',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='liveconcert',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddField(
            model_name='liveconcert',
            name='normal_ticket_price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=8),
        ),
        migrations.AddField(
            model_name='liveconcert',
            name='province_fee',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
        ),
        migrations.AddField(
            model_name='liveconcert',
            name='vvip_ticket_price',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=8),
        ),
        migrations.AlterField(
            model_name='liveconcert',
            name='vip_ticket_price',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=8),
        ),
    ]
