# Generated by Django 5.0 on 2025-11-20 08:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_remove_liveconcert_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theaterseat',
            options={'ordering': ['screen', 'row', 'number']},
        ),
        migrations.AddField(
            model_name='moviescreen',
            name='seats_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moviescreen',
            name='executive_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='moviescreen',
            name='normal_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='moviescreen',
            name='premium_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='theaterseat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='moviescreen',
            unique_together={('movie', 'screen_name')},
        ),
    ]
