# Generated by Django 5.0 on 2025-11-20 08:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0012_alter_theaterseat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theaterseat',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='moviescreen',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='moviescreen',
            name='executive_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='moviescreen',
            name='normal_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='moviescreen',
            name='premium_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='theaterseat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=4),
        ),
        migrations.RemoveField(
            model_name='moviescreen',
            name='seats_generated',
        ),
    ]
