# Generated by Django 5.0 on 2025-11-20 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0013_alter_theaterseat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveConcertTicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('VVIP', 'VVIP Ticket'), ('VIP', 'VIP Ticket'), ('COUPLES', 'Couples Ticket'), ('NORMAL', 'Normal Ticket')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='eventapp.liveconcert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='eventapp.user')),
            ],
        ),
    ]
