# Generated by Django 5.0 on 2025-11-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0014_liveconcertticketbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('regular', 'Regular'), ('offer', 'Offer'), ('fasttrack', 'Fasttrack')], max_length=20)),
                ('sub_category', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('senior', 'Senior Citizen'), ('student', 'Student Offer'), ('defence', 'Defence Family'), ('fasttrack_adult_buffet', 'Fasttrack Adult + Buffet'), ('fasttrack_child_buffet', 'Fasttrack Child + Buffet'), ('fasttrack_adult', 'Fasttrack Adult'), ('fasttrack_child', 'Fasttrack Child')], max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Discount %')),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('age_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('height_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('id_proof_required', models.BooleanField(default=False)),
                ('amusement_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='eventapp.amusementpark')),
            ],
        ),
    ]
