# Generated by Django 5.0 on 2025-11-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0015_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='AmusementTicket',
        ),
    ]
