# Generated by Django 5.0 on 2025-11-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0018_alter_amusementbookingitem_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amusementbookingitem',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventapp.amusementticket'),
        ),
    ]
