# Generated by Django 5.0 on 2025-11-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0019_alter_amusementbookingitem_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amusementbookingitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='amusementbookingitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=18.0, editable=False, max_digits=5),
        ),
    ]
