# Generated by Django 5.0 on 2025-11-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0021_alter_amusementbookingitem_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComedyShowSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('VIP_EARLY_A_E', 'VIP Early bird (A-E)'), ('VIP_EARLY_F_M', 'VIP Early bird (F-M)'), ('PREMIUM', 'Premium'), ('BALCONY', 'Balcony')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_booked', models.BooleanField(default=False)),
                ('comedy_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='eventapp.comedyshow')),
            ],
        ),
        migrations.CreateModel(
            name='BookingComedyShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('booking_date', models.DateTimeField()),
                ('ticket_price_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comedy_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.comedyshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.user')),
                ('seats', models.ManyToManyField(to='eventapp.comedyshowseat')),
            ],
        ),
    ]
