# Generated by Django 5.0 on 2025-11-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0023_alter_bookingcomedyshow_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcomedyshow',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='bookingcomedyshow',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='bookingcomedyshow',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='bookingcomedyshow',
            name='gst_percentage',
        ),
        migrations.RemoveField(
            model_name='bookingcomedyshow',
            name='ticket_price_total',
        ),
        migrations.AddField(
            model_name='bookingcomedyshow',
            name='number_of_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingcomedyshow',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='comedyshow',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingcomedyshow',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='ComedyShowSeat',
        ),
    ]
