# Generated by Django 5.0 on 2025-11-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0025_bookingsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to='eventapp.user'),
        ),
    ]
