# Generated by Django 5.0 on 2025-11-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0026_alter_bookingsevent_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingsevent',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Event Booking', 'verbose_name_plural': 'Event Bookings'},
        ),
        migrations.AlterField(
            model_name='bookingsevent',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
