# Generated by Django 5.0 on 2025-11-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0027_alter_bookingsevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
