# Generated by Django 5.0 on 2025-11-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0028_event_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
